/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DraAmandaRouteImport } from './routes/dra-amanda'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClinicaRouteImport } from './routes/clinica'
import { Route as IndexRouteImport } from './routes/index'

const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DraAmandaRoute = DraAmandaRouteImport.update({
  id: '/dra-amanda',
  path: '/dra-amanda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaRoute = ClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/contato': typeof ContatoRoute
  '/dra-amanda': typeof DraAmandaRoute
  '/journal': typeof JournalRoute
  '/resultados': typeof ResultadosRoute
  '/tratamentos': typeof TratamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/contato': typeof ContatoRoute
  '/dra-amanda': typeof DraAmandaRoute
  '/journal': typeof JournalRoute
  '/resultados': typeof ResultadosRoute
  '/tratamentos': typeof TratamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/contato': typeof ContatoRoute
  '/dra-amanda': typeof DraAmandaRoute
  '/journal': typeof JournalRoute
  '/resultados': typeof ResultadosRoute
  '/tratamentos': typeof TratamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinica'
    | '/contato'
    | '/dra-amanda'
    | '/journal'
    | '/resultados'
    | '/tratamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinica'
    | '/contato'
    | '/dra-amanda'
    | '/journal'
    | '/resultados'
    | '/tratamentos'
  id:
    | '__root__'
    | '/'
    | '/clinica'
    | '/contato'
    | '/dra-amanda'
    | '/journal'
    | '/resultados'
    | '/tratamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicaRoute: typeof ClinicaRoute
  ContatoRoute: typeof ContatoRoute
  DraAmandaRoute: typeof DraAmandaRoute
  JournalRoute: typeof JournalRoute
  ResultadosRoute: typeof ResultadosRoute
  TratamentosRoute: typeof TratamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dra-amanda': {
      id: '/dra-amanda'
      path: '/dra-amanda'
      fullPath: '/dra-amanda'
      preLoaderRoute: typeof DraAmandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica': {
      id: '/clinica'
      path: '/clinica'
      fullPath: '/clinica'
      preLoaderRoute: typeof ClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicaRoute: ClinicaRoute,
  ContatoRoute: ContatoRoute,
  DraAmandaRoute: DraAmandaRoute,
  JournalRoute: JournalRoute,
  ResultadosRoute: ResultadosRoute,
  TratamentosRoute: TratamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
